### PR TITLE
Bugfix/user permissions

### PR DESCRIPTION
**Pull request by hanaum**
These are the methods needed to update how users are added and removed on the front-end (KXW-710).

### CODE REVIEW

**Comment by UnsungHero97** [comment]
actually, it'd be better if you remove this class entirely. `PermissionChangeVisitor` needs to go away. I recommend implementing these in `ChannelService`, invoking them there directly, and remove all references to `PermissionChangeVisitor`.

**Comment by UnsungHero97** [comment]
when you delete `PermissionChangeVisitor`, don't forget to also remove this entry from `webpack.config.js`:

    'kryptnostic.permission-change-visitor': 'tree/PermissionChangeVisitor.coffee'

**Comment by hanaum** [comment]
Ok. Will do.

**Comment by hanaum** [comment]
There is actually a component of KTE that uses PermissionChangeVisitor so I will refactor that first and get back to this.

**Comment by UnsungHero97** [comment]
looks good to me. ship it!

**Pull request merged**
