### PR TITLE
Feature/search sharing

### PR DESCRIPTION
**Pull request by rbuckheit**
wip - do not merge
==============

### CODE REVIEW

**Comment by rbuckheit** [comment]
this code became outdated.

@makosblade and @hristo (I can't tag Hristo - has he been added to our org)? This may be useful to revive as part of search sharing implementation work.

**Comment by hristo** [comment]
I think you've got the wrong Hristo ;).
Please send my regards to Hristo Oskov.

Best,
Hristo

**Comment by UnsungHero97** [comment]
@hristo, hi! I'm jealous you got the "hristo" tag :)

@rbuckheit, I should be a part of the org now!

**Comment by hristo** [comment]
@UnsungHero97 :) btw, congrats on the new job!

**Pull request closed without merging**
