### PR TITLE
route object GETs to cdn.kodex.im (CloudFlare cache)

### PR DESCRIPTION
**Pull request by UnsungHero97**
Tier 1 URLs
- `/object/id/(id)/(version)`
- `/keys/aes`
- `/keys/aes/cryptoservice/id/(id)/(version)`

Tier 2 URLs
- `/keys/fhe/private`
- `/keys/fhe/searchprivate`
- `/keys/rsa/public/(id)`

### CODE REVIEW

**Comment by UnsungHero97** [comment]
@geekbeast @makosblade please take a look

**Comment by makosblade** [comment]
Why the tier 1 vs tier 2 split? Just for mental organization?

I dunno if we actually want to cache /keys/aes/cryptoservice/id/(id)/(version) cause sometimes we update cryptoservices right? I'll let @geekbeast comment on that one.

**Comment by makosblade** [comment]
LGTM

**Comment by UnsungHero97** [comment]
yes, mental organization. tier 1 requests are ones that are made most frequently, would have largest impact on performance. tier 2 requests happen less frequently (once), and/or have heavy responses.

good point on the AES crypto services. @geekbeast, thoughts?

**Comment by makosblade** [comment]
yeah, not 100% sure if we actually change them but I thought we did at some point :-/

**Comment by geekbeast** [comment]
We don't change crypto-services without re-writing the object on a new version.

**Pull request merged**
