### PR TITLE
do not encrypt client hash functions.

### PR DESCRIPTION
**Pull request by rbuckheit**
do not encrypt client hash functions
===========================

per @RobinZ16 these are given to the server in raw (unencrypted) form.

@RobinZ16 and @howpenghui please confirm that this is correct and that sending unencrypted hash function to the server is the desired behavior before I merge. Also, the PDF says to RSA encrypt it, so please update if that is the case.

@makosblade for CR as well.

### CODE REVIEW

**Comment by RobinZ16** [comment]
looks good!

**Comment by kryptodoge** [comment]
Yes, don't encrypt it.

**Comment by kryptodoge** [comment]
WHOOOOO

**Comment by kryptodoge** [comment]
Tester 1 2

**Comment by kryptodoge** [comment]
TEST 3 4

**Pull request merged**
