### PR TITLE
Feature/search sharing integration

### PR DESCRIPTION
**Pull request by howpenghui**
Persist a real engine upon auth and retrieve it upon usage. 
Sharing part not merged into this branch.

### CODE REVIEW

**Comment by howpenghui** [comment]
Don't pull for now.

**Comment by RobinZ16** [comment]
still in progress?

**Comment by UnsungHero97** [comment]
yea, I think @howpenghui  is still working on this branch

**Comment by RobinZ16** [comment]
@howpenghui said that this pr should never be merged...?

**Pull request merged**
